import type { NewCompatibilityRuleDefinition } from "../schema/compatibility.js";
import { getSpecificationDefinitionId } from "./specification-definitions.seed.js";
import { stableUuid } from "./shared.js";

export const compatibilityRuleSeeds: NewCompatibilityRuleDefinition[] = [
  {
    id: stableUuid("rule:frame-motor-mount-pattern"),
    key: "frame-motor-mount-pattern",
    name: "Frame motor mount matches motor mount",
    description: "Frame motor mount pattern must match the selected motor mount pattern.",
    fromCategoryKey: "FRAME",
    toCategoryKey: "MOTOR",
    leftSpecificationId: getSpecificationDefinitionId("motorMountPattern"),
    operator: "EQ",
    rightSpecificationId: getSpecificationDefinitionId("mountPattern"),
    severityOnFail: "INCOMPATIBLE",
    successMessageTemplate: "Motor mount pattern matches the frame.",
    failureMessageTemplate: "Motor mount pattern does not match frame mount pattern.",
    warningThresholdJson: null,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: stableUuid("rule:frame-prop-size-limit"),
    key: "frame-prop-size-limit",
    name: "Frame max prop size supports propeller",
    description: "Frame max prop size must be greater than or equal to the selected propeller size.",
    fromCategoryKey: "FRAME",
    toCategoryKey: "PROPELLER",
    leftSpecificationId: getSpecificationDefinitionId("maxPropSize"),
    operator: "GTE",
    rightSpecificationId: getSpecificationDefinitionId("size"),
    severityOnFail: "INCOMPATIBLE",
    successMessageTemplate: "Propeller size fits within frame clearance.",
    failureMessageTemplate: "Propeller size exceeds the frame's maximum supported prop size.",
    warningThresholdJson: null,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: stableUuid("rule:frame-esc-stack-mount"),
    key: "frame-esc-stack-mount",
    name: "Frame stack mount matches ESC stack mount",
    description: "Frame stack mount must match the selected ESC stack mount.",
    fromCategoryKey: "FRAME",
    toCategoryKey: "ESC",
    leftSpecificationId: getSpecificationDefinitionId("stackMount"),
    operator: "EQ",
    rightSpecificationId: getSpecificationDefinitionId("stackMount"),
    severityOnFail: "INCOMPATIBLE",
    successMessageTemplate: "ESC stack mount matches the frame.",
    failureMessageTemplate: "ESC stack mount does not match the frame's stack mount.",
    warningThresholdJson: null,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: stableUuid("rule:esc-motor-current-headroom"),
    key: "esc-motor-current-headroom",
    name: "ESC current rating supports motor max current",
    description: "ESC current rating must be greater than or equal to motor max current draw.",
    fromCategoryKey: "ESC",
    toCategoryKey: "MOTOR",
    leftSpecificationId: getSpecificationDefinitionId("currentRating"),
    operator: "GTE",
    rightSpecificationId: getSpecificationDefinitionId("maxCurrent"),
    severityOnFail: "INCOMPATIBLE",
    successMessageTemplate: "ESC current rating supports the motor.",
    failureMessageTemplate: "ESC current rating is lower than the motor's maximum current draw.",
    warningThresholdJson: { minHeadroomAmps: 5 },
    isActive: true,
    sortOrder: 4,
  },
  {
    id: stableUuid("rule:esc-battery-supported-voltage"),
    key: "esc-battery-supported-voltage",
    name: "ESC supported voltage contains battery cell count",
    description: "ESC supported voltage range must contain the battery cell count.",
    fromCategoryKey: "ESC",
    toCategoryKey: "BATTERY",
    leftSpecificationId: getSpecificationDefinitionId("supportedVoltage"),
    operator: "RANGE_CONTAINS",
    rightSpecificationId: getSpecificationDefinitionId("cellCount"),
    severityOnFail: "INCOMPATIBLE",
    successMessageTemplate: "Battery voltage is supported by the ESC.",
    failureMessageTemplate: "Battery voltage exceeds ESC supported voltage range.",
    warningThresholdJson: { warnAtUpperBound: true },
    isActive: true,
    sortOrder: 5,
  },
  {
    id: stableUuid("rule:motor-battery-supported-voltage"),
    key: "motor-battery-supported-voltage",
    name: "Motor supported voltage contains battery cell count",
    description: "Motor supported voltage range must contain the battery cell count.",
    fromCategoryKey: "MOTOR",
    toCategoryKey: "BATTERY",
    leftSpecificationId: getSpecificationDefinitionId("supportedVoltage"),
    operator: "RANGE_CONTAINS",
    rightSpecificationId: getSpecificationDefinitionId("cellCount"),
    severityOnFail: "INCOMPATIBLE",
    successMessageTemplate: "Battery voltage is supported by the motor.",
    failureMessageTemplate: "Battery voltage is outside the motor's supported range.",
    warningThresholdJson: { warnAtUpperBound: true },
    isActive: true,
    sortOrder: 6,
  },
  {
    id: stableUuid("rule:motor-recommended-prop-size"),
    key: "motor-recommended-prop-size",
    name: "Motor recommended prop size matches propeller size",
    description: "Motor recommended prop size should match the selected propeller size.",
    fromCategoryKey: "MOTOR",
    toCategoryKey: "PROPELLER",
    leftSpecificationId: getSpecificationDefinitionId("recommendedPropSize"),
    operator: "EQ",
    rightSpecificationId: getSpecificationDefinitionId("size"),
    severityOnFail: "WARNING",
    successMessageTemplate: "Propeller size matches the motor recommendation.",
    failureMessageTemplate: "Propeller size differs from the motor's recommended prop size.",
    warningThresholdJson: null,
    isActive: true,
    sortOrder: 7,
  },
];
