import type { NewSpecificationDefinition } from "../schema/specifications.js";
import { stableUuid } from "./shared.js";

export const specificationDefinitionSeeds = [
  {
    id: stableUuid("spec:wheelbase"),
    key: "wheelbase",
    name: "Wheelbase",
    description: "Distance between motor centers on the frame.",
    dataType: "NUMBER",
    unit: "mm",
    validationJson: { min: 100, max: 400 },
    searchWeight: 8,
    isFilterable: true,
    isSearchable: true,
  },
  {
    id: stableUuid("spec:maxPropSize"),
    key: "maxPropSize",
    name: "Max Prop Size",
    description: "Largest propeller diameter supported by the frame.",
    dataType: "NUMBER",
    unit: "inch",
    validationJson: { min: 2, max: 10 },
    searchWeight: 9,
    isFilterable: true,
    isSearchable: true,
  },
  {
    id: stableUuid("spec:stackMount"),
    key: "stackMount",
    name: "Stack Mount",
    description: "Stack mounting pattern supported by the frame or ESC.",
    dataType: "ENUM",
    unit: null,
    validationJson: { options: ["20x20", "30x30"] },
    searchWeight: 7,
    isFilterable: true,
    isSearchable: true,
  },
  {
    id: stableUuid("spec:motorMountPattern"),
    key: "motorMountPattern",
    name: "Motor Mount Pattern",
    description: "Frame motor mount hole pattern.",
    dataType: "ENUM",
    unit: null,
    validationJson: { options: ["9x9", "12x12", "16x16", "19x19"] },
    searchWeight: 7,
    isFilterable: true,
    isSearchable: true,
  },
  {
    id: stableUuid("spec:kv"),
    key: "kv",
    name: "KV",
    description: "Motor KV rating.",
    dataType: "NUMBER",
    unit: "KV",
    validationJson: { min: 800, max: 5000 },
    searchWeight: 9,
    isFilterable: true,
    isSearchable: true,
  },
  {
    id: stableUuid("spec:maxCurrent"),
    key: "maxCurrent",
    name: "Max Current",
    description: "Peak motor current draw.",
    dataType: "NUMBER",
    unit: "A",
    validationJson: { min: 5, max: 100 },
    searchWeight: 6,
    isFilterable: true,
    isSearchable: false,
  },
  {
    id: stableUuid("spec:supportedVoltage"),
    key: "supportedVoltage",
    name: "Supported Voltage",
    description: "Supported battery cell count range.",
    dataType: "RANGE",
    unit: "S",
    validationJson: { min: 2, max: 8 },
    searchWeight: 9,
    isFilterable: true,
    isSearchable: true,
  },
  {
    id: stableUuid("spec:mountPattern"),
    key: "mountPattern",
    name: "Mount Pattern",
    description: "Motor base mounting pattern.",
    dataType: "ENUM",
    unit: null,
    validationJson: { options: ["9x9", "12x12", "16x16", "19x19"] },
    searchWeight: 7,
    isFilterable: true,
    isSearchable: true,
  },
  {
    id: stableUuid("spec:recommendedPropSize"),
    key: "recommendedPropSize",
    name: "Recommended Prop Size",
    description: "Motor's recommended propeller diameter.",
    dataType: "NUMBER",
    unit: "inch",
    validationJson: { min: 2, max: 10 },
    searchWeight: 7,
    isFilterable: true,
    isSearchable: true,
  },
  {
    id: stableUuid("spec:currentRating"),
    key: "currentRating",
    name: "Current Rating",
    description: "ESC continuous current rating.",
    dataType: "NUMBER",
    unit: "A",
    validationJson: { min: 10, max: 120 },
    searchWeight: 8,
    isFilterable: true,
    isSearchable: true,
  },
  {
    id: stableUuid("spec:cellCount"),
    key: "cellCount",
    name: "Cell Count",
    description: "Battery pack cell count.",
    dataType: "NUMBER",
    unit: "S",
    validationJson: { min: 2, max: 8 },
    searchWeight: 9,
    isFilterable: true,
    isSearchable: true,
  },
  {
    id: stableUuid("spec:capacity"),
    key: "capacity",
    name: "Capacity",
    description: "Battery capacity.",
    dataType: "NUMBER",
    unit: "mAh",
    validationJson: { min: 300, max: 5000 },
    searchWeight: 7,
    isFilterable: true,
    isSearchable: false,
  },
  {
    id: stableUuid("spec:dischargeRating"),
    key: "dischargeRating",
    name: "Discharge Rating",
    description: "Battery discharge rating in C.",
    dataType: "NUMBER",
    unit: "C",
    validationJson: { min: 30, max: 150 },
    searchWeight: 6,
    isFilterable: true,
    isSearchable: false,
  },
  {
    id: stableUuid("spec:size"),
    key: "size",
    name: "Size",
    description: "Propeller diameter.",
    dataType: "NUMBER",
    unit: "inch",
    validationJson: { min: 2, max: 10 },
    searchWeight: 9,
    isFilterable: true,
    isSearchable: true,
  },
  {
    id: stableUuid("spec:pitch"),
    key: "pitch",
    name: "Pitch",
    description: "Propeller pitch.",
    dataType: "NUMBER",
    unit: null,
    validationJson: { min: 1.5, max: 6 },
    searchWeight: 5,
    isFilterable: true,
    isSearchable: false,
  },
] satisfies NewSpecificationDefinition[];

export type SpecificationKey = (typeof specificationDefinitionSeeds)[number]["key"];

export const specificationDefinitionIdByKey = Object.fromEntries(
  specificationDefinitionSeeds.map((definition) => [definition.key, definition.id]),
) as Record<SpecificationKey, string>;

export const specificationDefinitionByKey = Object.fromEntries(
  specificationDefinitionSeeds.map((definition) => [definition.key, definition]),
) as Record<SpecificationKey, (typeof specificationDefinitionSeeds)[number]>;

export function getSpecificationDefinitionId(key: SpecificationKey): string {
  return specificationDefinitionIdByKey[key]!;
}

export function getSpecificationDefinition(key: SpecificationKey) {
  return specificationDefinitionByKey[key]!;
}
